### ISSUE TITLE
issue with current/capacity/energy values

### ISSUE THREAD

**Issue by hitduyao** [FTHuld/neware_reader#7]
Hi there,

Thank you so much for this useful tool for converting nda file to csv. I had some success converting our nda file. But I found that only voltage value matches, current/capacity/energy values are all twice of that exported from Neware software. Any clue or instruction? BTW, when I use your test data, I found no such issue. Look forward to your reply. Thank you so much.

Thanks,
Yao

**Comment by FTHuld** [comment]
Hi @hitduyao 

Which version of the software are you using?
 
Could you share an example of some data that's giving you this issue? If you put it on google drive or something and then attach the link here I'll take a look at it.

**Comment by hitduyao** [comment]
Hi @FTHuld,

I'm using BTSClient8.0.  Sorry, I was unable to share the data. But I feel the issue comes from the variable current multiplier. It's likely no longer as 5 for small current and 50 for large current. But I don't know how to check the numbers from my nda file. I had a trial by removing the variable current multiplier. It corrects part of the issue. But some of the current be comes tenth of that from the software csv file. Any clue? Can you instruct on how to check the variable current multiplier from the software or my nda file? Thanks!

**Comment by FTHuld** [comment]
Hi @hitduyao 

Sorry for the long wait. We have switched to version 8.0 now too, and I managed to generate some of my own data.

I can confirm the issue that you encountered, and have uploaded a fix that works with my data. However, since my dataset is quite small, I can't be sure that it works for all test.

Let me know if it works.
